version: "3.8"
services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      # local port : port inside container
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
